// flow-typed signature: 114b0d5a732f3ae97741f271c88acbe9
// flow-typed version: <<STUB>>/babel-preset-node8_v^1.2.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-node8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-node8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-node8/index' {
  declare module.exports: $Exports<'babel-preset-node8'>;
}
declare module 'babel-preset-node8/index.js' {
  declare module.exports: $Exports<'babel-preset-node8'>;
}
